### PR TITLE
Fix erroneous duplicated message in dnssec01 test

### PR DESCRIPTION
**Pull request by vlevigneron**
Fix issue zonemaster/zonemaster-engine#694

### CODE REVIEW

**Comment by sandoche2k** [comment]
I just added the new code and tested :http://vps803736.ovh.net/result/ea3bce6e5bf754a7. It does not seem to be Ok

**Comment by vlevigneron** [comment]
In fact, it works but some messages "seems" to be the same, while they are not. For instance il you refer to "The DNSKEY with tag 12412 uses algorithm number 8 (RSA/SHA-256), which is OK.", it is tested on all name server and you will have the same message for each server. It could be optimized or we could add the address/name of server in message but it is different from the issue we have fixed here.

**Comment by matsduf** [comment]
If you follow the link http://vps803736.ovh.net/result/ea3bce6e5bf754a7 provided by @sandoche2k you see e.g. the following message "a.ns.se/192.36.144.107 returned a DS record created by algorithm 1/SHA-1, which is OK. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se." which is not the expected.

**Comment by vlevigneron** [comment]
Very strange because here is what I get from the CLI:
   8.27 ERROR     DNSSEC       a.ns.se/192.36.144.107 returned a DS record created by algorithm 1 (SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.27 INFO      DNSSEC       a.ns.se/192.36.144.107 returned a DS record created by algorithm 2 (SHA-256), which is OK. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.31 INFO      DNSSEC       b.ns.se/192.36.133.107 returned a DS record created by algorithm 2 (SHA-256), which is OK. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.31 ERROR     DNSSEC       b.ns.se/192.36.133.107 returned a DS record created by algorithm 1 (SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.36 ERROR     DNSSEC       c.ns.se/192.36.135.107 returned a DS record created by algorithm 1 (SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.36 INFO      DNSSEC       c.ns.se/192.36.135.107 returned a DS record created by algorithm 2 (SHA-256), which is OK. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.

**Comment by matsduf** [comment]
@vlevigneron, is that with or without your patch?

It is strange because with CLI the issue does only appears with --json, not with standrad output or --raw.

**Comment by vlevigneron** [comment]
@matsduf Really ? With the patch here is the output I get:
```
[...]
 {
    "args": {
      "address": "192.36.144.107",
      "algorithm_mnemonic": "SHA-256",
      "algorithm_number": 2,
      "keytag": 12412,
      "ns": "a.ns.se",
      "rrtype": "DS",
      "zone": "xn--rttgift-exa.se"
    },
    "level": "INFO",
    "module": "DNSSEC",
    "tag": "DS_ALGORITHM_OK",
    "timestamp": 8.24093294143677
  },
  {
    "args": {
      "address": "192.36.144.107",
      "algorithm_mnemonic": "SHA-1",
      "algorithm_number": 1,
      "keytag": 12412,
      "ns": "a.ns.se",
      "rrtype": "DS",
      "zone": "xn--rttgift-exa.se"
    },
    "level": "ERROR",
    "module": "DNSSEC",
    "tag": "DS_ALGORITHM_DEPRECATED",
    "timestamp": 8.24191308021545
  },
[...]
```

**Comment by matsduf** [comment]
> @matsduf Really ? With the patch here is the output I get:

I meant the original issue decribed in #694. It did not show up with standard output or with "--raw", only with "--json".

**Comment by vlevigneron** [comment]
@matsduf I just checked, it was visible with standard output
```
   8.24 ERROR     DNSSEC       a.ns.se/192.36.144.107 returned a DS record created by algorithm (1/SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
   8.28 ERROR     DNSSEC       b.ns.se/192.36.133.107 returned a DS record created by algorithm (1/SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
```
and in raw mode

```
   8.34 ERROR     DNSSEC       DNSSEC:DS_ALGORITHM_DEPRECATED address=192.36.144.107; algorithm_mnemonic=SHA-1; algorithm_number=1; keytag=12412; ns=a.ns.se; rrtype=DS; zone=xn--rttgift-exa.se
   8.38 ERROR     DNSSEC       DNSSEC:DS_ALGORITHM_DEPRECATED address=192.36.133.107; algorithm_mnemonic=SHA-1; algorithm_number=1; keytag=12412; ns=b.ns.se; rrtype=DS; zone=xn--rttgift-exa.se
```
And when the patch is apply, I see no longer the issue with standard/raw/json CLI output.

**Comment by matsduf** [comment]
> @matsduf I just checked, it was visible with standard output

I do not see it.

> ```
>    8.24 ERROR     DNSSEC       a.ns.se/192.36.144.107 returned a DS record created by algorithm (1/SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
>    8.28 ERROR     DNSSEC       b.ns.se/192.36.133.107 returned a DS record created by algorithm (1/SHA-1), which is deprecated. The DS record is for the DNSKEY record with keytag 12412 in zone xn--rttgift-exa.se.
> ```

Two messages concerning two different name servers, both stating that SHA-1 is deprecated. As expected.

> and in raw mode
> 
> ```
>    8.34 ERROR     DNSSEC       DNSSEC:DS_ALGORITHM_DEPRECATED address=192.36.144.107; algorithm_mnemonic=SHA-1; algorithm_number=1; keytag=12412; ns=a.ns.se; rrtype=DS; zone=xn--rttgift-exa.se
>    8.38 ERROR     DNSSEC       DNSSEC:DS_ALGORITHM_DEPRECATED address=192.36.133.107; algorithm_mnemonic=SHA-1; algorithm_number=1; keytag=12412; ns=b.ns.se; rrtype=DS; zone=xn--rttgift-exa.se
> ```

Same as above, as expected.

> And when the patch is apply, I see no longer the issue with standard/raw/json CLI output.

Fine. I will also test. When @sandoche2k tested it was not solved. I do not know why.

**Comment by vlevigneron** [comment]
Perhaps I should do the tests later, we are on the middle of a major production delivery. It seems i'm not focused enough on Zonemaster... :-)

**Comment by matsduf** [comment]
> Perhaps I should do the tests later, we are on the middle of a major production delivery. It seems i'm not focused enough on Zonemaster... :-)

Do that. I will test the patch, both in CLI and in Backend. I will post my findings here.

**Comment by vlevigneron** [comment]
@matsduf No I did not find out why there were duplicate messages in version not patched... :-/

**Pull request merged**
