### PR TITLE
Fix implementation of Syntax06

### LINKED ISSUE #669: Improper implementation of Syntax06
The current implementation of SYNTAX06 uses a public resolver to make to MX lookup. The test spec says that we should make the recursion ourselves and respect fake delegation.

### PR DESCRIPTION
**Pull request by tgreenx**
## Purpose

This PR removes the use of a public resolver for test case [Syntax06](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax06.md).

## Context

Fixes #669 

## How to test this PR

```
zonemaster-cli --test SYNTAX/syntax06 --show-testcase --level INFO --raw zonemaster.fr
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
   0.82 INFO      SYNTAX06       RNAME_RFC822_VALID   rname=hostmaster@nic.fr
```
```
zonemaster-cli --test SYNTAX/syntax06 --show-testcase --level INFO --raw syntax01.zut-root.rd.nic.fr
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
   2.05 WARNING   SYNTAX06       RNAME_RFC822_INVALID   rname=hostmaster@vps430859@ovh.net
   2.05 WARNING   SYNTAX06       RNAME_RFC822_INVALID   rname=hostmaster@vps430859@ovh.net
```

### CODE REVIEW

**Comment by tgreenx** [comment]
@matsduf @mattias-p I have been updating the unit tests data files as it is needed in this PR since it changes the recursion process. It has been successful for all except one,[ `t/Test-syntax06-L.t`](https://github.com/zonemaster/zonemaster-engine/blob/master/t/Test-syntax06-L.t). See below, the A record is missing for "cname1.exempelvis.se." but is expected according to the unit test. Do you have control over that zone and if so can you resolve the issue? Otherwise this unit test will have to be removed in order to pass checks.
(Note that I don't have an IPv6 connectivity right now thus the 'NO_RESPONSE' for IPv6 queries)

```
~/zonemaster/zonemaster-engine$ ZONEMASTER_RECORD=1 perl t/Test-syntax06-L.t
ok 1 - use Zonemaster::Engine;
ok 2 - use Zonemaster::Engine::Test::Syntax;
ok 3 - use Zonemaster::Engine::Util;

ns1.l.syntax06.exempelvis.se/2a02:750:12:77::97
ns1.l.syntax06.exempelvis.se/2a02:750:12:77::97

ns1.l.syntax06.exempelvis.se/46.21.97.97
msb@mail.l.syntax06.exempelvis.se
mail.l.syntax06.exempelvis.se
ns1.l.syntax06.exempelvis.se/46.21.97.97 | cname1.exempelvis.se.

ns2.l.syntax06.exempelvis.se/194.18.226.122
msb@mail.l.syntax06.exempelvis.se
mail.l.syntax06.exempelvis.se
ns2.l.syntax06.exempelvis.se/194.18.226.122 | cname1.exempelvis.se.

ns2.l.syntax06.exempelvis.se/2001:2040:2b:1c13::53
ns2.l.syntax06.exempelvis.se/2001:2040:2b:1c13::53
not ok 4 - should not emit NO_RESPONSE
#   Failed test 'should not emit NO_RESPONSE'
#   at t/Test-syntax06-L.t line 28.
ok 5 - should not emit NO_RESPONSE_SOA_QUERY
ok 6 - should not emit RNAME_RFC822_INVALID
not ok 7 - should not emit RNAME_MAIL_DOMAIN_INVALID
#   Failed test 'should not emit RNAME_MAIL_DOMAIN_INVALID'
#   at t/Test-syntax06-L.t line 31.
not ok 8 - should emit RNAME_RFC822_VALID
#   Failed test 'should emit RNAME_RFC822_VALID'
#   at t/Test-syntax06-L.t line 32.
1..8

~/zonemaster/zonemaster-engine$ dig cname1.exempelvis.se.

; <<>> DiG 9.16.22-Debian <<>> cname1.exempelvis.se.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 60152
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 62b218bb61ae5c0f01000000627cc60e15a2651f8c83aa61 (good)
;; QUESTION SECTION:
;cname1.exempelvis.se.          IN      A

;; AUTHORITY SECTION:
exempelvis.se.          3600    IN      SOA     bill.ip.se. msb.ip.se. 2022020900 21600 3600 604800 86400
```

**Review by matsduf — COMMENTED** [review]
Unit tests fail, else it looks good.

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
> Bump. Domain is still unreachable to this date.
> 
> ```
> dig cname1.exempelvis.se.
> [ ... ]
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9458
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> 
> [ ... ]
> ;; QUESTION SECTION:
> ;cname1.exempelvis.se.          IN      A
> 
> ;; AUTHORITY SECTION:
> exempelvis.se.          3600    IN      SOA     bill.ip.se. msb.ip.se. 2022020900 21600 3600 604800 86400
> 
> [ ... ]
> ;; WHEN: Tue Aug 02 16:22:01 CEST 2022
> [ ... ]
> ```
> 
> > Unit tests fail, else it looks good.
> 
> Yes, cf. my message above (from 12 May 2022).

So what is the expected resolution of cname1.exempelvis.se?

**Comment by tgreenx** [comment]
> So what is the expected resolution of cname1.exempelvis.se?

It should responds with NOERROR and A / AAAA records pointing to the mail domain, i.e reach steps [3.13.1.3](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax06.md?plain=1#85) of the specification.

**Comment by matsduf** [comment]
> > So what is the expected resolution of cname1.exempelvis.se?
> 
> It should respond with NOERROR and A / AAAA records pointing to the mail domain, i.e reach steps [3.13.1.3](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax06.md?plain=1#85) of the specification.

So the expected is rather to go to 3.12.1.3 or is it OK to go to 3.12.1.3?
```
cname1.exempelvis.se.   MX  1 hostname.
hostname.                        A     x.x.x.x
```

I have asked for help to investigate.

**Comment by matsduf** [comment]
> > > So what is the expected resolution of cname1.exempelvis.se?
> > 
> > 
> > It should respond with NOERROR and A / AAAA records pointing to the mail domain, i.e reach steps [3.13.1.3](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax06.md?plain=1#85) of the specification.
> 
> So the expected is rather to go to 3.12.1.3 or is it OK to go to 3.12.1.3?
> 
> ```
> cname1.exempelvis.se.   MX  1 hostname.
> hostname.                        A     x.x.x.x
> ```
> 
> I have asked for help to investigate.

Now it should be correct:
```
$ zonemaster-cli l.syntax06.exempelvis.se --test syntax/syntax06 --level INFO --show-testcase --raw
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.5.1
   1.00 INFO      SYNTAX06       RNAME_RFC822_VALID   rname=msb@mail.l.syntax06.exempelvis.se
```

**Comment by tgreenx** [comment]
> [ ...]
> 
> Now it should be correct:
> 
> ```
> $ zonemaster-cli l.syntax06.exempelvis.se --test syntax/syntax06 --level INFO --show-testcase --raw
>    0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.5.1
>    1.00 INFO      SYNTAX06       RNAME_RFC822_VALID   rname=msb@mail.l.syntax06.exempelvis.se
> ```

I concur, thanks. Tests should pass now.

**Review by matsduf — APPROVED** [review]

**Comment by mattias-p** [comment]
@matsduf Do we know why the reference zone changed? It makes me feel a bit uneasy.

**Comment by matsduf** [comment]
> @matsduf Do we know why the reference zone changed? It makes me feel a bit uneasy.

Human mistake. It stresses the need of documented test zones.

**Pull request merged**
