### PR TITLE
Remove unused message tag

### PR DESCRIPTION
**Pull request by pnax**
## Purpose

Remove an unused message tag.

## Context

Follow-up on #1034

## Changes

Remove a message tag.

## How to test this PR

Nothing much since the message is not used anywhere.

### CODE REVIEW

**Review by matsduf — APPROVED** [review]
Is the typo in the specification too?

**Comment by marc-vanderwal** [comment]
After further investigation, this message tag is not used anymore. Pull request #1034 updated test case ZONE11 to emit `N11_RETURNS_UNKNOWN_OPTION_CODE` instead of `UNKNOWN_OPTION_CODE`, but forgot to delete the message tag definition.

Running `git grep '\<UNKNOWN_OPTION_CODE\>'` confirms that the tag is used nowhere else in the code and could be safely deleted.

**Comment by marc-vanderwal** [comment]
> Is the typo in the specification too?

I found no occurrence of “ENDS” in [the new specification](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/Nameserver-TP/nameserver11.md). The previous version didn’t seem to have the typo either.

**Comment by pnax** [comment]
Thanks for checking for the tag usage (and the `git grep` tip). I've removed it.

**Review by marc-vanderwal — APPROVED** [review]
Looks good to me.

**Review by tgreenx — APPROVED** [review]

**Comment by pnax** [comment]
> Is the typo in the specification too?

No, but I found the same typo in zonemaster/zonemaster, see https://github.com/zonemaster/zonemaster/pull/1124

**Review by matsduf — APPROVED** [review]

**Pull request merged**
