### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by vlevigneron**
For Test cases
- Basic04
- DNSSEC15
- DNSSEC16
- DNSSEC16

### CODE REVIEW

**Comment by matsduf** [comment]
@pnax, can you reveiw this translation into French?

**Review by pnax — APPROVED** [review]

**Comment by pnax** [comment]
A question though, I noticed that the circumflex `^` is missing for some words (`etre`, `meme`). Is it done on purpose or is it just missing ?

**Comment by vlevigneron** [comment]
@pnax It's simpler than that... One of my keyboards is broken (^ key does not work any longer). I have to fix it. It seems I used this wrong keyboard to add some translations. If you are on this file, you can ropose a fix or I'll do that later.

**Comment by pnax** [comment]
I see :)
I've done a fix for the one I've caught.

**Comment by matsduf** [comment]
Resolves #912.

**Pull request merged**
