### PR TITLE
Recursor

### PR DESCRIPTION
**Pull request by mattias-p**
This is a bugfix PR in the wake of zonemaster/zonemaster#625.

First of all, this PR aligns the emission of IS_A_RECURSOR entries with what's prescribed by zonemaster/zonemaster#625.

Second, zonemaster/zonemaster#625 also changes the meaning of NO_RECURSOR so that it's old message strings are no longer appropriate. This PR updates the NO_RECURSOR msgid to an appropriate one and also updates its english and swedish msgstrs. Note that for danish and french I just used the english msgstr.

Third, with zonemaster/zonemaster#625 RECURSIVITY_UNDEF disappeared in a puff of logic. This PR cleans up its remains.

### CODE REVIEW

**Comment by mattias-p** [comment]
@sandoche2k Could you review this PR? Or have someone else do it or invite @bombsimon so he can do it.

**Comment by sandoche2k** [comment]
@bombsimon please review

**Comment by mattias-p** [comment]
@sandoche2k, if you want @bombsimon's review to count towards the required number reviews for approval, you must invite him to become a contributor. Alternatively you can make me an admin so I can invite him.

**Comment by sandoche2k** [comment]
@mattias-p You are owner for all repositories :-)

**Comment by mattias-p** [comment]
@sandoche2k I didn't know I was a Maintainer. I wasn't last time I checked and I just assumed nothing had changed. Sorry for bothering you about it. And thanks for the approval. I'll add the French translation in a separate PR. The danish one looks wrong to me and I think it's better to have it properly fixed.

**Pull request merged**
