### PR TITLE
- Fix zonemaster/zonemaster-engine#480

### PR DESCRIPTION
**Pull request by vlevigneron**
- Wrongly used extended-rcode/rcode in EDNS testing.

### CODE REVIEW

**Comment by sandoche2k** [comment]
It rectifies the issue https://github.com/zonemaster/zonemaster-engine/issues/480

**Comment by vlevigneron** [comment]
@sandoche2k @matsduf @mattias-p Is it reasonnable for all of you ?

**Comment by sandoche2k** [comment]
@vlevigneron i have already approved.

**Comment by sandoche2k** [comment]
@vlevigneron can you merge. If there is any issue, we can rollback.

**Pull request merged**
