### PR TITLE
New translation to spanish language.

### PR DESCRIPTION
**Pull request by huguei**
Sorry, I had to delete previous PR. Now it's rebased to develop. Thanks.

### CODE REVIEW

**Comment by matsduf** [comment]
@huguei, there are some new messages (msgid) that does not complete translation if matched against the code. These are new messages. Can you rebase your PR on current version of develop branch? And then update with `./update-po es.po`?

Can you then try to fix the messages marked "fuzzy" and the ones that are untranslated? See https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation-translators.md

**Comment by matsduf** [comment]
The file `MANIFEST` has to be updated. Can you add the line
```
share/locale/es/LC_MESSAGES/Zonemaster-Engine.mo
```
just after the existing line
```
share/locale/da/LC_MESSAGES/Zonemaster-Engine.mo
```
and push that?

**Comment by huguei** [comment]
Done changes to MANIFEST.

**Comment by matsduf** [comment]
> Done changes to MANIFEST.

Great!

**Review by matsduf — APPROVED** [review]

**Pull request merged**
