### PR TITLE
Add test case description in Engine

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

Make test case descriptions available in Engine.

## Context

https://github.com/zonemaster/zonemaster-gui/pull/341
https://github.com/zonemaster/zonemaster-backend/pull/1055

## Changes

* Adds test case descriptions
* Add method in translator to fetch the translated description for a given test case id.
TODO: unit test

## How to test this PR

```
% perl -MZonemaster::Engine::Translator -e 'my $t = Zonemaster::Engine::Translator->new; print $t->test_case_description("BASIC00") . "\n";'
Domain name must be valid
```

### CODE REVIEW

**Comment by matsduf** [comment]
The following error seems to come from this PR:
```
t/pod-coverage.t .......... 1/? 
#   Failed test 'Zonemaster::Engine::Translator'
#   at t/pod-coverage.t line 39.
#          got: '0.666666666666667'
#     expected: '1'
# Function 'test_case_description' not documented
# Looks like you failed 1 test of 27.
t/pod-coverage.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/27 subtests 
```

**Comment by blacksponge** [comment]
> The following error seems to come from this PR:

It should be fixed now.

**Comment by matsduf** [comment]
When I test using "how to test" I get unexpected result:
```
perl -MZonemaster::Engine::Translator -e 'my $t = Zonemaster::Engine::Translator->new; print $t->test_case_description("BASIC00") . "\n";'
Domain name must be valid
```

**Comment by matsduf** [comment]
I have found a character coding issue that I have reported in https://github.com/zonemaster/zonemaster-backend/pull/1055.  But it might belong to this PR instead.

**Review by pnax — APPROVED** [review]

**Review by marc-vanderwal — DISMISSED** [review]
Looks good to me.

**Review by matsduf — CHANGES_REQUESTED** [review]
I have found a character coding issue that I have reported in https://github.com/zonemaster/zonemaster-backend/pull/1055. But it might belong to this PR instead. Before this is merged it should be investigated.

**Comment by blacksponge** [comment]
> I have found a character coding

The encoding issue has been fixed in https://github.com/zonemaster/zonemaster-backend/pull/1055.

> When I test using "how to test" I get unexpected result:

This is the expected result, the description for `BASIC00` is `Domain name must be valid`

**Review by matsduf — DISMISSED** [review]
The issue that I reported in https://github.com/zonemaster/zonemaster-backend/pull/1055 has been resolved. There are some conflicts that must be fixed before this can be merged, but this looks fine.

**Comment by matsduf** [comment]
@blacksponge, please resolve the conflicts and I will re-approve.

**Comment by blacksponge** [comment]
I rebased on top of develop.

**Review by matsduf — APPROVED** [review]

**Review by tgreenx — COMMENTED** [review]
In `%TAG_DESCRIPTIONS` (all modules), `@_` is not needed as no parameters are ever given. But I don't think it can be an issue so I can approve as is, unless you want to make the changes.

**Comment by blacksponge** [comment]
> In %TAG_DESCRIPTIONS (all modules), @_ is not needed as no parameters are ever given. But I don't think it can be an issue so I can approve as is, unless you want to make the changes.

I chose to keep the `@_` to be consistent with the other descriptions

**Review by tgreenx — APPROVED** [review]

**Pull request merged**
