### PR TITLE
- Add method name (test case) in Logger.

### PR DESCRIPTION
**Pull request by vlevigneron**
- Add method name (test case) in Logger.
- Fixes zonemaster/zonemaster-engine#578

DO NOT MERGE NOW, do a test first to check if it is what you are waiting for

### CODE REVIEW

**Review by mattias-p — APPROVED** [review]
The code looks good to me.

**Comment by matsduf** [comment]
@sandoche2k,  can you ask @pnax, to verify if this will be a problem for backend or not?

**Comment by vlevigneron** [comment]
Just to chek before I merge. Can you confirm that we decided to merge this PR even if we are not sure of the impacts in CLI and Backend ??

**Comment by matsduf** [comment]
> Just to chek before I merge. Can you confirm that we decided to merge this PR even if we are not sure of the impacts in CLI and Backend ??

@vlevigneron, please merge. We will have to test anyway.

**Pull request merged**
