### PR TITLE
- Missing spaces in message

### PR DESCRIPTION
**Pull request by vlevigneron**
- Fixes zonemaster/zonemaster-engine#822

### CODE REVIEW

**Comment by matsduf** [comment]
If we have a patch release with #845, should this one be included too?

**Comment by matsduf** [comment]
@vlevigneron, I changed target branch from master to develop.

**Review by mattias-p — APPROVED** [review]
LGTM

**Comment by vlevigneron** [comment]
> @vlevigneron, I changed target branch from master to develop.

My mistake...

**Comment by matsduf** [comment]
I have tagged this for next full release, v2020.2, which means that it should not be merged now.

**Comment by matsduf** [comment]
I guess this needs rebasing to make Travis happy.

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
@vlevigneron, if you could rebase I could approve and you can merge.

**Review by matsduf — APPROVED** [review]

**Pull request merged**
