### PR TITLE
Added support for Norwegian language in test results

### PR DESCRIPTION
**Pull request by repperille**
This is the first version of the translation of the test results to Norwegian.

### CODE REVIEW

**Comment by matsduf** [comment]
@repperille, thank you for your contribution. Your write that it is the "first version". Does that mean that you expect that it will require further updates or just that this the first time with Norweigian for Zonemaster?

A second comment, before we have reviewed or merged, is that this messages are changing all the time. While the test cases are being updated, the messages must also be updated. I hope that we can count on you to help with translation work in the future.

**Comment by repperille** [comment]
@matsduf, by first version I meant the first time with a complete translation to Norwegian language. I have been working for some time in my fork adding and refining the translations.

I am committed to update the nb.po file when needed.

I see that there were two translation entries that still had the "fuzzy" attribute set. I have removed them and committed to my fork.
Shall I make a new PR or update this PR?

**Comment by matsduf** [comment]
> @matsduf, by first version I meant the first time with a complete translation to Norwegian language. I have been working for some time in my fork adding and refining the translations.

Fine!

> I am committed to update the nb.po file when needed.

Fine!

> I see that there were two translation entries that still had the "fuzzy" attribute set. I have removed them and committed to my fork.
> Shall I make a new PR or update this PR?

In your PR there are so many commits. If you know how to rebase on the current develop branch and create just one or two commits of everything I think it would be good. You do not have to create a new PR, just force push that to your branch.

If you find it to be easier, then create a new PR, but then I suggest that you create a new branch on your github fork to make it possible to add addition commits, if needed.

Your contribution is really welcome. It will be fun to expand with more languages.

**Comment by repperille** [comment]
I will create a new PR from a branch in my fork (the correct way to do it)

**Comment by matsduf** [comment]
Replaced by #751

**Pull request closed without merging**
