### PR TITLE
installation: libmodule-install-perl is also required

### PR DESCRIPTION
**Pull request by fanf2**

### CODE REVIEW

**Comment by sandoche2k** [comment]
If you are testing, please clone from the develop branch, all ZM modules, which has the recent updates w.r.t to EDNS and DNS flag day. We will be very grateful for your feedback.

**Comment by matsduf** [comment]
@fanf2, did you install from CPAN or from source? I think module-install is only needed when you install from source, so if you run `sudo cpanm Zonemaster::LDNS` then you should not need it.

Please correct me if I am wrong.

**Comment by matsduf** [comment]
Thank you for a detailed report. We will investigate.

**Comment by sandoche2k** [comment]
@fanf2 is right. I was substituting earlier using cpan with inc::Module::Install.

**Comment by mattias-p** [comment]
@fanf2 Thank you so much for contributing! And our apologies for taking so long.

**Pull request merged**
