### PR TITLE
Update message argument names in PO files

### PR DESCRIPTION
**Pull request by mattias-p**
The main thing here is that I've run update-po after merging #792 and adjusted all msgstr strings accordingly.

This PR also includes a few other fixes:
* Correction of an error I made in #792.
* A new make target (`tidy-po`) for tidying up the formatting in PO files without changing their substance.
* Tidying up of the formatting int the PO files.
* Maintenance of phony targets in `share/Makefile`.

### CODE REVIEW

**Comment by matsduf** [comment]
I assume that you want this to be merged with the v2020.1 release.

The new tydy-po command (target) will tidy all PO files, won't it? It will mean that it is not the best for the translators. Or what is your idea?

**Comment by mattias-p** [comment]
I created `make tidy-po` to help out with my own workflow in making this PR. I guess it could be nice for translators as well.

**Review by sandoche2k — APPROVED** [review]

**Review by matsduf — APPROVED** [review]
If you could provide the PO file to tidy, then it would be nice for all translators and could be integrated in the instructions for the translators, e.g.
```
make tidy-po sv.po
```

**Comment by mattias-p** [comment]
I created #797 regarding the creation of a translator friendly tidy tool.

**Pull request merged**
