### PR TITLE
Implementation of revised version of DNSSEC10

### LINKED ISSUE #632: Print meaningful message when algorithm is not supported by Zonemaster-LDNS/OpenSSL
If Zonemaster-LDNS and OpenSSL does not support the handling of a specific algorithm a confusing message "Unknown cryptographic algorithm" is printed, except if that algorithm is GOST, then "no GOST support" is printed.

Extend the GOST model to the following algorithms in all cases where the algorithm is used in such a way that the message can be generated.

Algorithm number | Algorithm (or description)
:----------------|:-----------------------------------
12               | GOST R 34.10-2001
13               | ECDSA Curve P-256 with SHA-256
14               | ECDSA Curve P-384 with SHA-384
15               | Ed25519
16               | Ed448

### PR DESCRIPTION
**Pull request by vlevigneron**
- Fixes zonemaster/zonemaster-engine#618
- Fixes zonemaster/zonemaster-engine#632
@matsduf As your english is far better than mine, do you have any proposal for this new messages (not yet included in the code) :
BROKEN_DNSSEC
INCONSISTENT_DNSSEC
INCONSISTENT_NSEC_NSEC3
MIXED_NSEC_NSEC3
NO_NSEC_NSEC3
TEST_ABORTED

**Please note that this PR only resolves #632 in respect to DNSSEC10.**

### CODE REVIEW

**Comment by matsduf** [comment]
Suggestions for the messages not yet in the code. The parameters should be adopted to what is normally used:

BROKEN_DNSSEC:
```
All nameservers for zone {zone} responds with neither NSEC nor NSEC3 records when such records are expected.
```

INCONSISTENT_DNSSEC:
```
Some, but not all, nameservers for zone {zone} respond with neither NSEC nor NSEC3 records when such records are expected.
```

INCONSISTENT_NSEC_NSEC3:
```
Some nameservers for zone {zone} respond with NSEC records and others respond with NSEC3 records. Consistency is expected.
```

MIXED_NSEC_NSEC3:
```
Nameserver {ns/address} for zone {zone} responds with both NSEC and NSEC3 records when only one record type is expected.
```

NO_NSEC_NSEC3:
```
Nameserver {ns/address} for zone {zone} responds with neither NSEC nor NSEC3 record when when such records are expected.
```

TEST_ABORTED
```
Nameserver {ns/address} for zone {zone} responds with RCODE "NOERROR" on a query that is expected to give response with RCODE "NXDOMAIN". Test for NSEC and NSEC3 is aborted for this nameserver.
```

**Comment by matsduf** [comment]
@vlevigneron, I will complete my review when you have incorporated the messages and resolved the conflicts (rebased?).

**Comment by vlevigneron** [comment]
@matsduf Done !

**Comment by vlevigneron** [comment]
@matsduf You are right, I only fixed zonemaster/zonemaster-engine#632 for DNSSEC10 in this PR. Sorry for the confusion. Do you think, I should also fixed that for all dnssec test cases in this PR or create a dedicated PR for this (except DNSSEC10 which is already done in this PR).

**Comment by matsduf** [comment]
> @matsduf You are right, I only fixed #632 for DNSSEC10 in this PR. Sorry for the confusion. Do you think, I should also fixed that for all dnssec test cases in this PR or create a dedicated PR for this (except DNSSEC10 which is already done in this PR).

I think it is better to limit a PR when possible. I will update the description of this PR and approved. After merging this PR, please create a PR resolving the rest of #632.

**Pull request merged**
