### PR TITLE
New test for consistency over CDS records. 

### PR DESCRIPTION
**Pull request by huguei**

### CODE REVIEW

**Comment by huguei** [comment]
I'll open a new PR over the development branch. Thanks.

**Comment by mattias-p** [comment]
FYI it's possible to change the target branch of an existing PR. A drop-down for that shows up when you press the edit button for the PR title.

**Comment by sandoche2k** [comment]
@huguei i moved it to the develop branch

**Comment by sandoche2k** [comment]
@huguei ignore my previous message. I see that you have made a new PR https://github.com/zonemaster/zonemaster-engine/pull/437.

**Pull request closed without merging**
