### PR TITLE
- Update Data in broken zones to pass unit tests.

### PR DESCRIPTION
**Pull request by vlevigneron**
## Purpose

This PR updates data file of DNSSEC unit tests.

## Context

Fixes zonemaster/zonemaster-engine#941

## Changes

Test-dnssec.data has been updated

## How to test this PR

use `make test`

### CODE REVIEW

**Comment by matsduf** [comment]
Can you create this against the patch-release-v2021.1.2 branch instead? We do not want to include the other changes in the develop branch for this patch.

**Review by matsduf — COMMENTED** [review]
If you can rebase this on the patch-release-v2021.1.2 branch instead I will approve. It works as it should.

**Comment by matsduf** [comment]
@vlevigneron, it is not enough to change the base. Can you rebase vlevigneron:fix-issue-zonemaster-engine-941 to be built on the patch-release-v2021.1.2 branch?

**Comment by vlevigneron** [comment]
I created a new PR zonemaster/zonemaster-engine#943
This one will be closed

**Comment by matsduf** [comment]
Replaced by #943.

**Pull request closed without merging**
