### PR TITLE
Add START/END messages in case of debug of test cases 

### PR DESCRIPTION
**Pull request by vlevigneron**
Fixes zonemaster/zonemaster-engine#665

Implementation not yet finished but can you confirm @matsduf that it is what you are waiting for (Only 3 modules for the moment Basic/Address/Connectivity). If it's OK, I'll finish with the other modules.

### CODE REVIEW

**Comment by vlevigneron** [comment]
@matsduf Yes I looked at zonemaster/zonemaster-engine#732 but the fact is that the messages MODULE_CALL are written outside of test case codes that's why they are there only when we run a unique test case. It can not be used if we want a START/END message for all test cases.

If it's OK for you, I'll add the messages for all test cases.

**Comment by matsduf** [comment]
> @matsduf Yes I looked at #732 but the fact is that the messages MODULE_CALL are written outside of test case codes that's why they are there only when we run a unique test case. It can not be used if we want a START/END message for all test cases.

I understand, and then I find it more or less worthless. I suggest that the code for the message MODULE_CALL is removed unless you see a reason to keep it (does not have to be done now). I wanted to make sure that you had not missed that and #732.

> If it's OK for you, I'll add the messages for all test cases.

Yes, it looks good. It will make it much easier to troubleshooting.

**Comment by vlevigneron** [comment]
@matsduf Finished. I'll remove MODULE_CALL in another PR related to zonemaster/zonemaster-engine#732

**Comment by vlevigneron** [comment]
@matsduf if you had to choose, what do you prefer, a full qualified method name (this is how it is implemented now) or the short version for testcase ?

>    0.01 DEBUG     SYSTEM       SYSTEM:MODULE_VERSION module=Zonemaster::Engine::Test::DNSSEC; version=v1.1.21
>   0.01 DEBUG     DNSSEC       DNSSEC:TEST_CASE_START testcase=Zonemaster::Engine::Test::DNSSEC::dnssec13

vs

>    0.01 DEBUG     SYSTEM       SYSTEM:MODULE_VERSION module=Zonemaster::Engine::Test::DNSSEC; version=v1.1.21
>   0.01 DEBUG     DNSSEC       DNSSEC:TEST_CASE_START testcase=dnssec13

**Comment by matsduf** [comment]
> @matsduf if you had to choose, what do you prefer, a full qualified method name (this is how it is implemented now) or the short version for testcase ?

The short version.

> > 0.01 DEBUG     SYSTEM       SYSTEM:MODULE_VERSION module=Zonemaster::Engine::Test::DNSSEC; version=v1.1.21

Here I guess that the long, explicit format makes sense.

> > 0.01 DEBUG     DNSSEC       DNSSEC:TEST_CASE_START testcase=dnssec13

Here it is better with short name. It will be easier to read. It is possible to derive the full name from the testcase.

**Comment by matsduf** [comment]
The changes look good so far. When completed, I will test.

**Pull request merged**
